FROM indexyz/php
LABEL maintainer="Indexyz <indexyz@protonmail.com>"

COPY . /var/www
WORKDIR /var/www

RUN cp config/.config.example.php config/.config.php 
RUN chmod -R 755 storage 
RUN chmod -R 777 /var/www/storage/framework/smarty/compile/ 
RUN curl -SL https://getcomposer.org/installer -o composer-setup.php 
RUN php composer-setup.php 
RUN php composer.phar install 
RUN php xcat initQQWry 
RUN php xcat initdownload 
RUN crontab -l | { cat; echo "30 22 * * * php /var/www/xcat sendDiaryMail"; } | crontab - 
RUN crontab -l | { cat; echo "0 0 * * * php /var/www/xcat dailyjob"; } | crontab - 
RUN crontab -l | { cat; echo "*/1 * * * * php /var/www/xcat checkjob"; } | crontab - 
RUN crontab -l | { cat; echo "*/1 * * * * php /var/www/xcat syncnode"; } | crontab - 
RUN { \
    echo '[program:crond]'; \
    echo 'command=cron -f'; \
    echo 'autostart=true'; \
    echo 'autorestart=true'; \
    echo 'killasgroup=true'; \
    echo 'stopasgroup=true'; \
    } | tee /etc/supervisor/crond.conf